--P25
SELECT * FROM T_STUDENT WHERE HEIGHT >180 OR HEIGHT = 180;
SELECT NAME ,WEIGHT FROM T_STUDENT WHERE WEIGHT > 59 AND WEIGHT < 81;
SELECT * FROM T_STUDENT WHERE DEPTNO1 IN (101,201);
SELECT * FROM T_STUDENT WHERE NAME LIKE '김%';

--P26
SELECT NAME ,GRADE ,HEIGHT FROM T_STUDENT WHERE GRADE =4 AND HEIGHT >170;
SELECT NAME ,HEIGHT ,GRADE , WEIGHT FROM T_STUDENT WHERE GRADE =1 OR WEIGHT >80;
SELECT NAME ,GRADE, HEIGHT ,WEIGHT FROM T_STUDENT WHERE GRADE =2 AND HEIGHT >180 AND WEIGHT >70;
SELECT NAME ,GRADE, HEIGHT ,WEIGHT FROM T_STUDENT WHERE GRADE =2 AND (HEIGHT >180 OR WEIGHT >70);
SELECT ENAME ,HIREDATE FROM T_EMP WHERE HIREDATE < '1992/01/01';

--P27
SELECT NAME ,BIRTHDAY ,HEIGHT ,WEIGHT FROM T_STUDENT ORDER BY BIRTHDAY ASC;
SELECT NAME 이름 ,HEIGHT 키 FROM T_STUDENT WHERE GRADE =1 ORDER BY NAME ASC;
SELECT NAME ,BIRTHDAY FROM T_EMP2 WHERE BIRTHDAY BETWEEN '1980/01/01' AND '1990/01/01';