--INITCAP() 함수
--#4101
SELECT INITCAP('pretty girl') "INITCAP 함수" FROM DUAL;

--#4102
SELECT ID ,INITCAP(ID) "INITCAP 함수적용" FROM T_STUDENT WHERE DEPTNO1 = 201;

--LOWER(),UPPER()
--#4103
SELECT NAME ,ID ,UPPER(ID) 대문자, LOWER(ID) 소문자 FROM T_STUDENT WHERE DEPTNO1 = 201;

--LENGTH()
--#4104
SELECT NAME, ID, LENGTH(ID) FROM T_STUDENT WHERE LENGTH(ID) > 9;

--LENGTH(),LENGTHB()
--#4105
SELECT NAME 이름, LENGTH(NAME) 길이, LENGTHB(NAME) 바이트 FROM T_STUDENT WHERE DEPTNO1 =201;

--CONCAT()
--#4106
SELECT CONCAT(NAME , POSITION) ,POSITION FROM  T_PROFESSOR WHERE DEPTNO =101;

--SUBSTR('ABCDE',2,3) -> ABCDE 중에서 2번째 문자부터 문자 3개 출력
SELECT SUBSTR('ABCDE',2,3) FROM  DUAL;
SELECT SUBSTR('ABCDE',20,3) FROM  DUAL; --NULL (error 아님)
SELECT SUBSTR('ABCDE',-2,3)FROM DUAL;

--substr()
--#4107
SELECT NAME,SUBSTR(JUMIN ,1,6) 생년월일 FROM T_STUDENT WHERE DEPTNO1 = 101;
SELECT NAME,SUBSTR(JUMIN ,1,6) FROM T_STUDENT WHERE SUBSTR(JUMIN ,3,2)='08'; 
SELECT NAME ,JUMIN FROM T_STUDENT WHERE GRADE = 4 AND (SUBSTR(JUMIN ,7,1)=2);

--INSTR()
SELECT INSTR('A*B*C*','*',1,1) FROM DUAL; --2
SELECT INSTR('A*B*C*','*',1,2) FROM DUAL; --4
SELECT INSTR('A*B*C*','*',3,2) FROM DUAL; --6
SELECT INSTR('A*B*C*','*',-4,1) FROM DUAL; --2 음수인덱스의 경우 검색도 음의 방향으로 진행
SELECT INSTR('A*B*C*','*',-4,2) FROM DUAL; --0 없으면 0 리턴 
SELECT INSTR('A*B*C*', '*', -2, 2) FROM dual;  -- 2

--#4110
SELECT NAME , TEL ,INSTR(TEL,')',1,1) AS 위치 FROM T_STUDENT WHERE DEPTNO1 = 101;

--#4111
SELECT NAME , TEL ,SUBSTR(tel, 1, INSTR(tel, ')') - 1) 지역번호
FROM T_STUDENT WHERE DEPTNO1 = 101;

--LTRIM(), RTRIM(), TRIM()
 SELECT
	LTRIM('슈퍼슈퍼슈가맨', '슈퍼') LTRIM,
	LTRIM('슈퍼슈퍼슈가맨', '슈') LTRIM,
	'   슈퍼슈가맨',
	LTRIM('   슈퍼슈가맨', ' ') LTRIM,
	LTRIM('   슈퍼슈가맨') LTRIM,
	-- 디폴트로 '공백' 제거
 	RTRIM('우측 공백 제거      ') RTRIM
 	TRIM('   슈퍼맨       ') TRIM --좌우 공백 제거 
FROM
	dual;

--#4113
SELECT LPAD(DNAME ,10,'1234') FROM t_dept2;

-- #4117
SELECT * FROM t_dept2;

SELECT dname, RTRIM(dname, '부') RTRIM예제
FROM t_dept2;

-- REPLACE 함수
SELECT REPLACE('슈퍼맨 슈퍼걸','슈퍼','파워') FROM DUAL;
SELECT REPLACE('아버지가 방에 들어간다', ' ', '') FROM dual;

-- #4118
SELECT NAME, REPLACE (NAME ,SUBSTR(NAME ,1,1),'#') "#학생"
FROM T_STUDENT WHERE DEPTNO1 = 102;

--#4119
SELECT REPLACE(NAME ,SUBSTR(NAME,2,1),'#') 학생 FROM T_STUDENT WHERE DEPTNO1 = 101;

SELECT NAME ,REPLACE(JUMIN ,SUBSTR(JUMIN ,7,7),'*******') FROM T_STUDENT WHERE DEPTNO1 =101;

SELECT NAME ,TEL ,REPLACE(TEL ,SUBSTR(TEL ,INSTR(TEL ,')')+1,3),'###') FROM T_STUDENT WHERE DEPTNO1 =102;

DROP TABLE student CASCADE CONSTRAINT;
DROP TABLE prof CASCADE CONSTRAINT;
DROP TABLE dept CASCADE CONSTRAINT;
CREATE TABLE student (
	STUDNO NUMBER PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	ID VARCHAR2(20) NOT NULL,
	GRADE NUMBER,
	DEPTNO NUMBER  REFERENCES dept(DEPTNO),
	PROFNO NUMBER REFERENCES prof(PROFNO)
);
CREATE TABLE prof(
	PROFNO NUMBER PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	ID VARCHAR2(20) NOT NULL,
	PAY NUMBER NOT NULL,
	DEPTNO NUMBER REFERENCES dept(DEPTNO)
);

CREATE TABLE dept(
	DEPTNO NUMBER PRIMARY KEY,
	DNAME VARCHAR2(20) NOT NULL
);
SELECT NAME 이름, PAY 급여 FROM T_PROFESSOR WHERE PAY > 5000;

INSERT INTO DEPT VALUES(101,'A');
INSERT INTO DEPT VALUES(102,'B');
INSERT INTO DEPT VALUES(103,'C');
INSERT INTO DEPT VALUES(104,'D');

INSERT INTO PROF VALUES (1001,'김교수','KIM',1000,101);
INSERT INTO PROF VALUES (1002,'신교수','KIM',1000,102);
INSERT INTO PROF VALUES (1003,'최교수','KIM',1000,103);
INSERT INTO PROF VALUES (1004,'이교수','KIM',1000,104);


INSERT INTO STUDENT(STUDNO,NAME,ID,DEPTNO,GRADE,PROFNO) VALUES (9091,'김수진','sooplus',101,2,1004);
INSERT INTO STUDENT(STUDNO,NAME,ID,DEPTNO,GRADE,PROFNO) VALUES (9090,'강수진','sooplus1',102,4,1003);
INSERT INTO STUDENT(STUDNO,NAME,ID,DEPTNO,GRADE,PROFNO) VALUES (9098,'최수진','sooplus2',103,4,1002);
INSERT INTO STUDENT(STUDNO,NAME,ID,DEPTNO,GRADE,PROFNO) VALUES (9097,'이수진','sooplus3',104,4,1001);
INSERT INTO STUDENT(STUDNO,NAME,ID,DEPTNO,GRADE,PROFNO) VALUES (9012,'양수진','sooplus3',104,4,1001);

SELECT * FROM student;

INSERT INTO PROF VALUES ();
DELETE FROM STUDENT WHERE GRADE = 4;

SELECT * FROM student;
SELECT * FROM prof;
SELECT * FROM dept;

SELECT p.name "교수님 이름",d.dname "소속 학과명" 
FROM prof.p,dept.d WHERE p.deptno = d.deptno;

SELECT DEPTNO FROM STUDENT WHERE NAME = '이수진';

SELECT name, deptno
FROM STUDENT 
WHERE DEPTNO  IN (SELECT DEPTNO FROM STUDENT WHERE NAME = '이수진');









