SELECT * FROM  TEST_MEMBER ;

--INSERT INTO TEST_MEMBER 
--UPDATE TEST_MEMBER SET 
--DELETE FROM TEST_MEMBER 

INSERT INTO TEST_MEMBER  VALUES(10,'남윤주',SYSDATE);
INSERT INTO TEST_MEMBER VALUES(22,'이승환','1994-02-21');
INSERT INTO TEST_MEMBER VALUES(17,'윤종섭','1999-12-01');
INSERT INTO TEST_MEMBER VALUES('','이예지','');
INSERT INTO TEST_MEMBER VALUES(NULL,'문상현','2011-05-23');


SELECT * FROM  TEST_MEMBER ;

--dBeaver 에서는 기본적으로 auto-COMMIT 수행